# Deleting Terraform on state alone isn't always possible:
# https://github.com/hashicorp/terraform/issues/5425#issuecomment-194395754
---
name: Terraform Destroy
description: Perform a Terraform destroy using the provided inputs.
branding:
  icon: file-minus
  color: red
inputs:
  dir:
    description: The working directory containing the Terraform project.
    default: "."
  workspace:
    description: Name of the Terraform workspace to use during the operation.
    required: false
  lock:
    description: Boolean which specifies if a state lock is to be held during the operation.
    default: "true"
  variables:
    description: YAML or JSON object containing key/value pairs specifying input values.
    required: false
  allow-undeclared:
    description: >-
      YAML or JSON list containing the names of variable keys which may safely be ignored
      when the are specified as input but are undeclared by the called Terrafrom project.
    required: false
  token:
    description: The GitHub PAT token to use for accessing remote Terraform modules stored on GitHub.
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: Terraform variables
      id: variables
      shell: bash
      run: |
        # Terraform variables
        set -eo pipefail
        variables_json="$(yq '. // {}' -o json <<<"${variables}" | jq -r 'if type == "object" then . else error("\"variables\" root element must be an object") end')"
        allow_undeclared_json="$(yq '. // []' -o json <<<"${allow_undeclared}" | jq -r 'if type == "array" then . else error("\"undeclared\" root element must be a list") end')"

        # Specify our multiline output using GH action flavored heredocs
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        {
            echo "variables-json<<EOF"
            jq <<<"${variables_json}"
            echo "EOF"

            echo "allow-undeclared-json<<EOF"
            jq <<<"${allow_undeclared_json}"
            echo "EOF"
        } | tee -a "$GITHUB_OUTPUT"
      env:
        variables: ${{ inputs.variables }}
        allow_undeclared: ${{ inputs.allow-undeclared }}
    - name: Terraform destroy
      shell: bash
      run: |
        # Destroy
        set -eo pipefail

        # Convert JSON variables into CLI flags or environmental variables. We'll remove
        # entries with `null` values as we cannot pass those into Terraform:
        # https://github.com/hashicorp/terraform/issues/29078
        #
        # TODO: Add tests for JSON lists and values with spaces. If you aren't very careful can end up
        # with `'-var=foo="a b"'` which looks like a positional argument to terraform.
        tf_var_flags=()
        tf_var_envs=()
        while read -r json; do
            key="$(jq -re '.key' <<<"${json}")"
            value="$(jq -re '.value | tostring' <<<"${json}")"

            if jq -e --arg key "$key" 'any(index($key))' <<<"${allow_undeclared_json}"; then
                tf_var_envs+=(TF_VAR_${key}="${value}")
            else
                tf_var_flags+=(-var "${key}=${value}")
            fi
        done < <(jq -cr 'to_entries[] | select(.value != null)' <<<"${variables_json}")

        echo "::group::terraform init"
        terraform init
        echo "::endgroup::"

        if [[ -n "$workspace" ]]; then
            # When the workspace doesn't exist then there are no resources to delete
            terraform workspace select "${workspace}" || exit 0
        fi

        echo "::group::terraform destroy"
        (set -x; env "${tf_var_envs[@]}" terraform destroy -auto-approve -lock="$lock" -input=false "${tf_var_flags[@]}")
        echo "::endgroup::"

        if [[ -n "$workspace" ]]; then
            # The "default" workspace always exists:
            # https://developer.hashicorp.com/terraform/language/state/workspaces#using-workspaces
            terraform workspace select default

            echo "::group::terraform workspace delete"
            terraform workspace delete "${workspace:?}"
            echo "::endgroup::"
        fi
      env:
        # Allow HTTPS token access to remote modules. Using environmental variables to
        # only temporarily modify the Git configuration.
        GIT_CONFIG_COUNT: "1"
        GIT_CONFIG_KEY_0: url.https://git:${{ inputs.token }}@github.com.insteadOf
        GIT_CONFIG_VALUE_0: https://github.com

        workspace: ${{ inputs.workspace }}
        lock: ${{ inputs.lock }}
        variables_json: ${{ steps.variables.outputs.variables-json }}
        allow_undeclared_json: ${{ steps.variables.outputs.allow-undeclared-json }}
      working-directory: ${{ inputs.dir }}
