---
name: Terraform Apply
description: Perform a Terraform plan and apply using the provided inputs.
branding:
  icon: file-plus
  color: green
inputs:
  dir:
    description: The working directory containing the Terraform project.
    default: "."
  workspace:
    description: Name of the Terraform workspace to use during the operation.
    required: false
  lock:
    description: Boolean which specifies if a state lock is to be held during the operation.
    default: "true"
  variables:
    description: YAML or JSON object containing key/value pairs specifying input values.
    required: false
  undeclared:
    description: >-
      YAML or JSON list containing the names of variable keys which may safely be ignored
      when the are specified as input but are undeclared by the called Terrafrom project.
    required: false
  token:
    description: The GitHub PAT token to use for accessing remote Terraform modules stored on GitHub.
    default: ${{ github.token }}
outputs:
  json:
    description: The raw JSON output provided by the Terraform output subcommand.
    value: ${{ steps.outputs.outputs.json }}
  json-kv:
    description: JSON object containing key/value pairs of output values.
    value: ${{ steps.outputs.outputs.json-kv }}
runs:
  using: composite
  steps:
    - name: Terraform variables
      id: variables
      shell: bash
      run: |
        # Terraform variables
        set -eo pipefail
        variables_json="$(yq '. // {}' -o json <<<"${variables}" | jq -r 'if type == "object" then . else error("root element must be an object") end')"
        undeclared_json="$(yq '. // []' -o json <<<"${variables}" | jq -r 'if type == "array" then . else error("root element must be a list") end')"

        # Specify our multiline output using GH action flavored heredocs
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        {
            echo "variables-json<<EOF"
            jq <<<"${variables_json}"
            echo "EOF"

            echo "undeclared-json<<EOF"
            jq <<<"${undeclared_json}"
            echo "EOF"
        } | tee -a "$GITHUB_OUTPUT"
      env:
        variables: ${{ inputs.variables }}
    - name: Terraform apply
      shell: bash
      run: |
        # Execute
        set -eo pipefail

        # Convert JSON variables into CLI flags or environmental variables. We'll remove
        # entries with `null` values as we cannot pass those into Terraform:
        # https://github.com/hashicorp/terraform/issues/29078
        #
        # TODO: Add tests for JSON lists and values with spaces. If you aren't very careful can end up
        # with `'-var=foo="a b"'` which looks like a positional argument to terraform.
        var_flags=()
        env_vars=()
        while read -r json; do
            key="$(jq -re '.key' <<<"${json}")"
            value="$(jq -re '.value | tostring' <<<"${json}")"

            if jq -e --arg key "$key" 'any(index($key))' <<<"${undeclared_json}"; then
                env_vars+=(TF_VAR_${key}="${value}")
            else
                var_flags+=(-var "${key}=${value}")
            fi
        done < <(jq -cr 'to_entries[] | select(.value != null)' <<<"${variables_json}")

        echo "::group::terraform init"
        terraform init
        echo "::endgroup::"

        if [[ -n "$workspace" ]]; then
            echo "::group::set workspace"
            terraform workspace select -or-create "${workspace:?}"
            echo "::endgroup::"
        fi

        echo "::group::terraform apply"
        (set -x; env "${env_vars[@]}" terraform apply -auto-approve -lock="$lock" -input=false "${var_flags[@]}")
        echo "::endgroup::"
      env:
        # Allow HTTPS token access to remote modules. Using environmental variables to
        # only temporarily modify the Git configuration.
        GIT_CONFIG_COUNT: "1"
        GIT_CONFIG_KEY_0: url.https://git:${{ inputs.token }}@github.com.insteadOf
        GIT_CONFIG_VALUE_0: https://github.com

        workspace: ${{ inputs.workspace }}
        lock: ${{ inputs.lock }}
        variables_json: ${{ steps.variables.outputs.variables-json }}
        undeclared_json: ${{ steps.variables.outputs.undeclared-json }}
      working-directory: ${{ inputs.dir }}
    - name: Terraform outputs
      id: outputs
      shell: bash
      run: |
        # Terraform outputs
        # https://developer.hashicorp.com/terraform/cli/commands/output
        json="$(terraform output -json)"

        # Specify our multiline output using GH action flavored heredocs
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        {
            echo "json<<EOF"
            jq <<<"${json:?}"
            echo "EOF"

            # Remove metadata from output
            echo "json-kv<<EOF"
            jq 'with_entries({key: .key, value: .value.value})' <<<"${json:?}"
            echo "EOF"
        } | tee -a "$GITHUB_OUTPUT"
      working-directory: ${{ inputs.dir }}
