---
name: Integration Tests
on:
  pull_request:
    paths:
      - "apply/action.yaml"
      - "destroy/action.yaml"
      - ".github/workflows/integration-tests.yaml"
  push:
    branches: ["main"]
    tags: ["*"]
    paths:
      - "apply/action.yaml"
      - "destroy/action.yaml"
      - ".github/workflows/integration-tests.yaml"

env:
  # Use separate Terraform workspaces for PRs, tags, and each commit on "main".
  workspace: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) ||
                (github.event_name == 'push' && (github.ref_type == 'tag' && format('tag-{0}', github.ref_name) || format('sha-{0}', github.sha)) ||
                'unknown') }}

jobs:
  test-web-server:
    name: Test Web Server
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          # Avoiding using Terraform 1.10 at this time as it does not work well with `apply --auto-approve`:
          # https://github.com/hashicorp/terraform/issues/36106#issuecomment-2506181760
          terraform_version: "~1.9"
      - name: Deploy Terraform resources
        id: terraform
        uses: ./apply
        with:
          dir: .github/terraform/web-server
          workspace: ${{ env.workspace }}
          variables: |-
            image: nginx:latest
      - name: Validate apply
        run: |
          status="$(curl -fsSL -o /dev/null -w "%{http_code}" http://localhost:8000)"
          if [[ "$status" -ne 200 ]]; then
              echo "status=$status"
              docker ps
              exit 1
          fi
      - name: Destroy Terraform resources
        uses: ./destroy
        with:
          dir: .github/terraform/web-server
          workspace: ${{ env.workspace }}
          variables: |-
            image: nginx:latest
      - name: Validate destroy
        run: |
          rc=0
          curl -fsSL http://localhost:8000 || rc=$?
          if [[ "$rc" -ne 7 ]]; then
              echo "rc=$rc"
              docker ps
              exit 1
          fi

  test-null-variable:
    name: Test Null Variable
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          # Avoiding using Terraform 1.10 at this time as it does not work well with `apply --auto-approve`:
          # https://github.com/hashicorp/terraform/issues/36106#issuecomment-2506181760
          terraform_version: "~1.9"
      - id: deploy-null
        uses: ./apply
        with:
          dir: .github/terraform/input-output
          variables: |-
            required: required
            optional: null
        continue-on-error: true
      - name: Validate
        run: |
          [[ "$outcome" == "success" ]] || exit 1
          jq -er '.optional == null' <<<"${json_kv}" || exit 1
        env:
          outcome: ${{ steps.deploy-null.outcome }}
          json_kv: ${{ steps.deploy-null.outputs.json-kv }}

  test-undeclared-variable:
    name: Test Undeclared Variable
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          # Avoiding using Terraform 1.10 at this time as it does not work well with `apply --auto-approve`:
          # https://github.com/hashicorp/terraform/issues/36106#issuecomment-2506181760
          terraform_version: "~1.9"
      - name: Deploy undeclared (failure)
        id: deploy-undeclared-failure
        uses: ./apply
        with:
          dir: .github/terraform/input-output
          variables: |-
            required: required
            dne: value undeclared for variable
        continue-on-error: true
      - name: Validate
        run: |
          [[ "$outcome" == "failure" ]] || exit 1
        env:
          outcome: ${{ steps.deploy-undeclared-failure.outcome }}
      - name: Deploy undeclared (allowed)
        id: deploy-undeclared-allowed
        uses: ./apply
        with:
          dir: .github/terraform/input-output
          variables: |-
            required: required
            dne: value undeclared for variable
          undeclared: |
            - dne
        continue-on-error: true
      - name: Validate
        run: |
          [[ "$outcome" == "success" ]] || exit 1
        env:
          outcome: ${{ steps.deploy-undeclared-allowed.outcome }}
      - name: Deploy undeclared (declared)
        id: deploy-undeclared-declared
        uses: ./apply
        with:
          dir: .github/terraform/input-output
          variables: |-
            required: required
            optional: foo
          undeclared: |
            - optional
        continue-on-error: true
      - name: Validate
        run: |
          [[ "$outcome" == "success" ]] || exit 1
        env:
          outcome: ${{ steps.deploy-undeclared-declared.outcome }}
