---
name: Integration Tests
on:
  pull_request:
    paths:
      - "apply/action.yaml"
      - "destroy/action.yaml"
      - ".github/workflows/integration-tests.yaml"
  push:
    branches: ["main"]
    tags: ["*"]
    paths:
      - "apply/action.yaml"
      - "destroy/action.yaml"
      - ".github/workflows/integration-tests.yaml"

env:
  # Use separate Terraform workspaces for PRs, tags, and each commit on "main".
  workspace: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) ||
                (github.event_name == 'push' && (github.ref_type == 'tag' && format('tag-{0}', github.ref_name) || format('sha-{0}', github.sha)) ||
                'unknown') }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          # Avoiding using Terraform 1.10 at this time as it does not work well with `apply --auto-approve`:
          # https://github.com/hashicorp/terraform/issues/36106#issuecomment-2506181760
          terraform_version: "~1.9"
      - name: Deploy Terraform resources
        id: terraform
        uses: ./apply
        with:
          dir: .github/terraform
          workspace: ${{ env.workspace }}
          variables: |-
            image: nginx:latest
            optional:
      - name: Validate apply
        run: |
          status="$(curl -fsSL -o /dev/null -w "%{http_code}" http://localhost:8000)"
          if [[ "$status" -ne 200 ]]; then
              echo "status=$status"
              docker ps
              exit 1
          fi
      - name: Destroy Terraform resources
        uses: ./destroy
        with:
          with:
          dir: .github/terraform
          workspace: ${{ env.workspace }}
          variables: |-
            image: nginx:latest
            optional:
      - name: Validate destroy
        run: |
          rc=0
          curl -fsSL http://localhost:8000 || rc=$?
          if [[ "$rc" -ne 7 ]]; then
              echo "rc=$rc"
              docker ps
              exit 1
          fi
